data_name: "FFmpeg"
vocab_size: 2000
max_len: 500
victim_model_path: "./victim_models/"
model_name: "word2vec_dnn"
tokenizer_path: "./embedding/tokenizer"
adv_test: "./result/test_after_adv"
model_max_len: 1000
batch_size: 32

MHM:
  max_iter: 100
  n_candidate: 30
  attack_range: 0.1
  time: 600